# Generated by Django 5.0.3 on 2024-03-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Employer',
        ),
    ]
