# Generated by Django 5.0.3 on 2024-03-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_rename_employer_worker'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='work',
            field=models.ManyToManyField(related_name='Worker', to='works.work'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
